### ISSUE TITLE
ToPlainText containing <br /> does not translate such tag in a \n new line

### ISSUE THREAD

**Issue by HKunogi** [CXuesong/MwParserFromScratch#24]
When using ToPlainText on nodes that contains text including <br /> which mediawiki uses to jump a line, the HtmlDecode call, strips out those tags directly, but would definitely be nice to have as an option (maybe function argument overload or something like this), a way to make so before stripping the html tags, it would replace all the <br />  tags for \n so new lines would be kept on the final plain text cleaned string.

**Comment by CXuesong** [comment]
Thanks for the issue! Fixed in [`v0.3.0-int.7`](https://github.com/CXuesong/MwParserFromScratch/releases/tag/v0.3.0-int.7).
